version: '3.8'

services:
  mariadb:
    build: ./requirements/mariadb/
    image: mariadb
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      -mariadb:/var/lib/mysql
    networks:
      - inception
  nginx:
    build: ./requirements/nginx/
    image: nginx
    restart: unless-stopped
    depends_on:
      - wordpress
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html
    ports:
      - "443:443"
    networks:
      - inception
  wordpress:
    build: ./requirements/wordpress/
    image: wordpress
    restart: unless-stopped
    depends_on:
      - mariadb
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
networks:
  inception:
volumes:
  wordpress:
    type: bind
    source: ~/wordpress_files
  mariadb:
    type: bind
    source: ~/dbase_data

  