version: '3.8'
services:
  mariadb:
    build: 
      context: ./requirements/mariadb/
      args:
        DB_PASS: ${DB_PASS}
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_ROOT_PASS: ${DB_ROOT_PASS}
    image: mariadb
    container_name: mariadb
    restart: unless-stopped
    env_file:
      - .env
    pull_policy: never
    volumes: 
      - db_vol:/var/lib/mysql
    networks:
      - inception
  nginx:
    build: ./requirements/nginx/
    image: nginx
    pull_policy: never
    container_name: nginx
    restart: unless-stopped
    depends_on:
      - wordpress
    env_file:
      - .env
    volumes:
      - /home/ahamdy/wordpress_vol:/var/www/html/
    ports:
      - "443:443"
    networks:
      - inception
  wordpress:
    build: ./requirements/wordpress/
    image: wordpress
    pull_policy: never
    container_name: wordpress
    restart: unless-stopped
    depends_on:
      - mariadb
    env_file:
      - .env
    volumes: 
      - /home/ahamdy/wordpress_vol:/var/www/html/
    networks:
      - inception
networks:
  inception:

volumes:
  db_vol:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/ahamdy/db_vol'
