 FROM debian:buster

 RUN apt update -y && apt install mariadb-server -y;
 
 COPY ./setup_db.sh /
 RUN chmod +x /setup_db.sh
 RUN sed -i "s/.*bind-address.*/bind-address = 0.0.0.0/" /etc/mysql/mariadb.conf.d/50-server.cnf
# RUN /setup_db.sh

 CMD ["/setup_db.sh"]
