 FROM debian:buster

 RUN apt update -y && apt install mariadb-server -y;
 
 COPY ./setup_db.sh /
 RUN chmod +x /setup_db.sh
 ARG DB_PASS=${DB_PASS}
 ARG DB_NAME=${DB_NAME}
 ARG DB_USER=${DB_USER}
 ARG DB_ROOT_PASS=${DB_ROOT_PASS}
 RUN sed -i "s/.*bind-address.*/bind-address = 0.0.0.0/" /etc/mysql/mariadb.conf.d/50-server.cnf
 RUN /setup_db.sh

CMD ["mysqld"]
#  CMD ["/setup_db.sh"]
