FROM debian:buster

RUN apt update -y
RUN  apt install php7.3 php7.3-fpm php7.3-mysql \
	php7.3-gd php7.3-xml php7.3-mbstring php7.3-curl curl -y
RUN apt install default-mysql-client -y
RUN curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar 
RUN chmod +x wp-cli.phar && mv wp-cli.phar /usr/local/bin/wp
COPY ./setup_wp.sh /
RUN chmod +x /setup_wp.sh

CMD ["/setup_wp.sh"]
# RUN /setup_wp.sh
# CMD ["php-fpm7.3"]