FROM debian:buster

RUN apt update -y
RUN  apt install php php-fpm php-mysql \
	php-gd php-xml php-mbstring php-curl curl sendmail -y
RUN apt install default-mysql-client -y
RUN curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar 
RUN chmod +x wp-cli.phar && mv wp-cli.phar /usr/local/bin/wp
COPY ./setup_wp.sh /
RUN chmod +x /setup_wp.sh

CMD ["/setup_wp.sh"]
