FROM debian:buster

RUN apt update && sudo apt -y upgrade
RUN  apt install php php-fpm php-mysql \
	php-gd php-xml php-mbstring php-curl curl -y
RUN curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar 
RUN chmod +x wp-cli.phar && mv wp-cli.phar /usr/local/bin/wp

